* fixed a bug in seq.window_search(window_size, step_size) caused a     "undefined method `+' for nil:NilClass (NoMethodError)"   error when seq.length is smaller than window_size