Workaround to avoid bug in old versions of Bundler
 * gemfiles/prepare-gemspec.rb: execute "gem update bundler" to avoid
   "NoMethodError: undefined method `spec' for nil:NilClass"
   during "bundle install". This error may be due to a bug of Bundler
   and the bug seems to be fixed in the latest version of Budler.