Bug fix: suppress NoMethodError when parsing CC lines
 * Bio::UniProtKB#cc: When parsing a nonexistent CC topic,
   "NoMethodError: undefined method `join' for nil:NilClass"
   was raised. To suppress the error, changed to return nil
   if the given data is nil.